config/routes.rb
Ludically::Application.routes.draw do
  root to: 'static_pages#home'

  scope "(/:locale)", locale: /fr|en/ do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]

    root to: 'static_pages#home'

    match '/help', to: 'static_pages#help'
    match '/about', to: 'static_pages#about'
    match '/contact', to: 'static_pages#contact'
    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

require "valid_email"

class User < ActiveRecord::Base

  include ActiveModel::Validations

  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, email: true, uniqueness: { case_sensitive: false }

# no need to test for presence again, that's done already with has_secure_password above
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  include HttpAcceptLanguage
  include SessionsHelper

  def set_locale
    I18n.locale = params[:locale] \
               || request.preferred_language_from(I18n.available_locales) \
               || request.compatible_language_from(I18n.available_locales)   \
               || I18n.default_locale
    logger.debug "* Locale set to '#{I18n.locale}'"
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = t :invalid_signin
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

	def about
	end

	def contact
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = t :welcome_new_user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		if page_title.empty?
			I18n.t :base_title
		else
			"#{I18n.t :base_title } | #{page_title}"
		end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options= { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to t(:about),   about_path %></li>
      <li><%= link_to t(:contact), contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to t(:app_name), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to t(:home),    root_path %></li>
          <li><%= link_to t(:help),    help_path %></li>
          <% if signed_in? %>
              <li><%= link_to t(:users), '#' %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t(:account) %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t(:profile), current_user %></li>
                  <li><%= link_to t(:settings), '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t(:sign_out), signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to t(:sign_in), signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <%= t :form_errors, count: @user.errors.count %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><i class="icon-remove-sign "></i> <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.fr.html.erb
<% provide(:title, t(:about_us)) %>
<h1><%= t :about_us %></h1>
<p>
  Nous somme Ludically, un éditeur de jeu excellent.
</p>

app/views/static_pages/about.html.erb
<% provide(:title, t(:about_us)) %>
<h1><%= t :about_us %></h1>
<p>
  We are Ludically, an awesome game publisher.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, t(:contact)) %>
<h1><%= t(:contact) %></h1>
<p>
  Contact us at <a href="mailto:contact@ludically.com">Ludically</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, t(:help)) %>
<h1><%= t(:help) %></h1>
<p>
  Help navigating this site.
</p>

app/views/static_pages/home.fr.html.erb
<div class="center hero-unit">
  <h1>Bienvenue à Ludically</h1>

  <h2>
    Vous êtes sur la page d'accueil de Ludically.
  </h2>

  <%= link_to t(:sign_up), signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Ludically</h1>

  <h2>
    You are on Ludically's home page.
  </h2>

  <%= link_to t(:sign_up), signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, t(:sign_up)) %>
<h1><%= t :sign_up %></h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <i class="icon-envelope"></i><%= f.label t(:email) %>
      <%= f.text_field :email %>

      <%= f.label t(:password) %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit t(:create_account), class: "btn btn-large btn-primary" %>
  <% end %>
  </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user, size: 200 %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<%= @user.name %>, <%= @user.email %>